const server1 = require("./Server");
const router = require("./Router");
var requestHandlers = require("./RequestHandlers");
var handle = {};
handle["/"] = requestHandlers.start;
handle["/start"] = requestHandlers.start;
handle["/upload"] = requestHandlers.upload;
handle["/find"] = requestHandlers.find;
handle["/show"] = requestHandlers.show;
handle["/login"] = requestHandlers.login;
handle["/logout"] = requestHandlers.logout;
server1.start(router.route, handle);
